# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
name: "Setup and validate environment"

outputs:
  fmtOutcome:
    description: 'Outcome of terraform fmt -check'
    value: ${{ jobs.validate.outputs.fmtOutcome }}
  initOutcome:
    description: 'Outcome of terraform init'
    value: ${{ jobs.validate.outputs.initOutcome }}
  validateOutcome:
    description: 'Outcome of terraform validate'
    value: ${{ jobs.validate.outputs.validateOutcome }}
  validateOutput:
    description: 'stdout of terraform validate'
    value: ${{ jobs.validate.outputs.validateOutput }}

runs:
  using: composite
  outputs:
    fmtOutcome: ${{ steps.fmt.outcome }}
    initOutcome: ${{ steps.init.outcome }}
    validateOutcome: ${{ steps.validate.outcome}}
    validateOutput: ${{ steps.validate.outputs.stdout}}
  steps:
    # ensure checkout step is run before calling this action
    - uses: 'moonrepo/setup-toolchain@v0'
      with:
        auto-install: true

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      shell: bash

    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
