name: "Validate merge"

on:
  push:
    branches:
      - master

jobs:
  validate_main_module:
    runs-on: ubuntu-latest
    name: "Validate module"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        id: setup

  validate_example_module:
    runs-on: ubuntu-latest
    name: "Validate example module"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        id: setup
        with:
          working-directory: 'example'
